tripal:
  version: 1.x
  css:
    theme:
      css/tripal.css: {}
  js:
    js/tripal.js: {}
  dependencies:
    - core/drupal
    - core/jquery
    - core/drupalSettings

jobs:
   css:
      theme:
         css/tripal.jobs.css: {}

tripal-toolbar:
  version: 1.x
  css:
    component:
      css/tripal.toolbar.css: {}

tripal-dashboard:
  version: 1.x
  js:
    js/tripal.dashboard.js: {}

d3:
  version: 1.x
  js:
    js/d3.v3.min.js: {}

uploader:
  version: 1.x
  js:
    js/TripalUploader.js: {}

upload-file:
  version: 1.x
  js:
    js/TripalUploadFile.js: {}

tripal-file:
  version: 1.x
  js:
    js/tripal.file.js: {}

vars:
  version: 1.x
  js:
    js/tripal.vars.js: {}
