# Run some PHPUnit tests
name: PHPUnit-Tests

# When do we want the tests to run?
on: [push, pull_request]

# Define jobs that are part of the workflow
jobs:
  # Job 1: 'build'
  run-tests:
    # Runner type
    runs-on: ubuntu-latest
    # PHP Targets
    strategy:
      matrix:
        dockertags: ['drupal8.9.11-dev']
    # Give the builds names so we can tell them apart
    name: PHPUnit Testing (TripalDocker ${{ matrix.dockertags }})

    # Steps in the sequence
    steps:
      # Check out the repo
      - name: Checkout Repository
        uses: actions/checkout@v2
      # Just spin up docker the good ol' fashion way.
      - name: Spin up Docker
        run: |
          docker run --publish=80:80 --name=tripaldocker -tid \
            --volume=`pwd`:/var/www/drupal8/web/modules/contrib/tripal \
            tripalproject/tripaldocker:${{ matrix.dockertags }}
          docker exec tripaldocker service postgresql restart
          docker exec tripaldocker drush cr
          docker exec tripaldocker drush trp-drop-chado --schema-name=chado
          docker exec tripaldocker drush trp-prep-tests
      # Runs the PHPUnit tests.
      # https://github.com/mheap/phpunit-github-actions-printer is used
      # to report PHPUnit fails in a meaningful way to github in PRs.
      - name: PHPUnit Tests
        env:
          SIMPLETEST_BASE_URL: "http://localhost"
          SIMPLETEST_DB: "pgsql://drupaladmin:drupal8developmentonlylocal@localhost/sitedb"
          BROWSER_OUTPUT_DIRECTORY: "/var/www/drupal8/web/sites/default/files/simpletest"
        run: |
          docker exec --workdir=/var/www/drupal8 tripaldocker composer require --dev mheap/phpunit-github-actions-printer
          docker exec tripaldocker service postgresql restart
          docker exec -e SIMPLETEST_BASE_URL=$SIMPLETEST_BASE_URL \
            -e SIMPLETEST_DB=$SIMPLETEST_DB \
            -e BROWSER_OUTPUT_DIRECTORY=$BROWSER_OUTPUT_DIRECTORY \
            tripaldocker phpunit --printer mheap\\GithubActionsReporter\\Printer \
              --configuration core modules/contrib/tripal
